on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: actions/upload-artifact@v2
       with:
        name: extension-builds
        path: dist/*.zip
  e2e-tests:
    needs: build
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
      - uses: actions/download-artifact@v3
        with:
          name: extension-builds
      - name: Extract extention
        run: unzip extension-builds.zip && unzip chrome.zip -d tests/chrome
      - name: Run Playwright tests
        run: xvfb-run npx playwright test
      - uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
