on:
  workflow_dispatch:

jobs:
  e2e-tests:
    name: Run e2e tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: npx playwright install-deps chromium
      - name: Run tests
        run: xvfb-run npx playwright test
