on:
  workflow_dispatch:

jobs:
  e2e-tests:
    name: Run e2e tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: | 
          cd tests
          npm ci
          npx playwright install-deps
          npx playwright install
      - name: Run tests
        working-directory: tests 
        run: xvfb-run npx playwright test
